Menu:
  Home: /
  Archives: https://github.com/Exia081?tab=repositories
  About: https://github.com/Exia081
  # Category: /category_archive
  # Tag: /tag_archive
  Github: https://github.com/Exia081
  Search: false

Site:
  Motto: 山重水复疑无路，柳暗花明又一村

Intro:
  Avastar: img/avatar.png
  Name: Exia
  Brief: 2015年计算机专业毕业,后端学习者
  SNS:
    Weibo:
    StackOverflow:
    Github: https://github.com/Exia081
    Pinterest:
    Quora:

CopyRight:
  Author: 山重水复疑无路，柳暗花明又一村
  License: CC BY-NC-SA 3.0 CN

Tip:
  Alipay:
  Wechat:

Comment:
  Id: 8d83609a651e972e308daa
  Secret: 37e40c89a47e957f654e86f71c5caaccad0774deaa
  Repo:
  Owner: Exia
